#!/bin/bash

. /etc/sysconfig/network
echo "var.HOSTNAME = \"$HOSTNAME\""

if [ "X$DAV_USERF" == "X" ]; then
    if [ -f $DAV_BASE/etc/krb5.keytab ]; then
        echo 'auth.backend.gssapi.keytab = env.DAV_BASE + "/etc/krb5.keytab"'
        echo 'auth.backend.gssapi.spnego = "enable"'
    else
        echo 'auth.backend.gssapi.spnego = "disable"'
    fi
fi

if [ "$DAV_DEV" == "1" ]; then
    echo "server.modules += ( \"mod_status\", \"mod_accesslog\" )"
    if [ "X$DAV_USERF" == "X" ]; then
        echo "status.status-url = \"/server-status-main\""
        echo "status.config-url = \"/server-config-main\""
        echo "status.statistics-url = \"/server-stats-main\""
        echo "accesslog.filename = \"${DAV_BASE}/run/frontend.log\""
    else
        echo "status.status-url = \"/server-status-user\""
        echo "status.config-url = \"/server-config-user\""
        echo "status.statistics-url = \"/server-stats-user\""
        echo "accesslog.filename = \"${DAV_BASE}/run/${DAV_USERF}.log\""
    fi
fi
