#!/usr/bin/python

import afsdav, os
from subprocess import call
from glob import glob
def cleanup():
    call(['pkill', '-9', '-f', 'backend'])
    for elt in glob(afsdav.RUN+'/*.sock'):
        try: os.kill(int(file(elt).read().strip()), 9)
        except: pass
        for k in ('err', 'k5', 'lock', 'pid', 'sock', 'tok', 'ttl'):
            try: os.unlink(elt[:-3]+k)
            except: pass
        try: os.unlink(elt)
        except: pass
    for elt in glob(afsdav.RUN+'/cache/*'):
        try: os.unlink(elt)
        except: pass
cleanup()

from threading import Thread
from afsdav import ticket_start
from time import sleep, time

class Angel(object):
    def __init__(self):
        self.proc = {}
        self._ttl = {}
        self._T = Thread(target=self._run)
        self._T.start()
        self._dead = False

    def __contains__(self, k): return k in self.proc
    def __del__(self):
        self._dead = True
        for k5 in self.proc:
            self.stop(k5)

    def start(self, k5, user):
        if k5 in self.proc: return
        self.proc[k5] = ticket_start(user, k5)
        self._ttl[k5] = int(file(k5[:-2]+'ttl').read())

    def stop(self, k5):
        if not k5 in self.proc: return
        p = self.proc[k5]
        del self.proc[k5]
        try:
            p.kill()
            p.wait()
        except: pass
        for elt in glob(k5[:-2]+'*'):
            try: os.unlink(elt)
            except: pass

    def _run(self):
        while not self._dead:
            sleep(3)
            self._gc()
    def _gc(self):
        now = int(time())
        for k, ttl in list(self._ttl.items()):
            if ttl < now:
                self.stop(k)

angel = Angel()

import pyinotify, asyncore
wm = pyinotify.WatchManager()
mask = pyinotify.IN_CREATE | pyinotify.IN_DELETE | pyinotify.IN_MODIFY | pyinotify.IN_MOVED_TO

from os.path import basename

class EventHandler(pyinotify.ProcessEvent):
    def process_IN_DELETE(self, event):
        angel.stop(event.pathname)

    def process_IN_CREATE(self, event):
        self.process_IN_MODIFY(event)
    def process_IN_MOVED_TO(self, event):
        self.process_IN_MODIFY(event)
    def process_IN_MODIFY(self, event):
        if event.pathname[-3:] != '.k5': return
        k5 = event.pathname
        angel.start(k5, basename(k5)[:-3])

notifier = pyinotify.AsyncNotifier(wm, EventHandler())
wm.add_watch(afsdav.RUN, mask, rec=True)
asyncore.loop()
